---
version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.33.3
    ports:
      - '9090:9090'
    volumes:
      - './prometheus.yml:/etc/prometheus/prometheus.yml'
      - './prometheus/data:/prometheus/data'
    command:
      --web.enable-lifecycle
      --web.enable-admin-api
      --config.file=/etc/prometheus/prometheus.yml
  node-exporter:
    image: prom/node-exporter:v1.3.1
    ports:
      - '9100:9100'
  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.69.0
    ports:
      - '8428:8428'
    volumes:
      - 'victoriametrics:/victoria-metrics-data'
    command:
      -storageDataPath=/victoria-metrics-data
      -retentionPeriod=30d
  grafana:
    image: grafana/grafana:8.3.6
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana

volumes:
  victoriametrics:
    driver: local
