---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: 'node'
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: 'victoriametrics'
    static_configs:
      - targets: ["victoriametrics:8428"]

# remote_write:
#   - url: http://victoriametrics:8428/api/v1/write
