---
global:
  resolve_timeout: 5m
  smtp_from: alertmanager@example.com
  smtp_smarthost: mailhog:1025

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: 'email'
    email_configs:
      - to: test@example.com
        require_tls: false
