---
version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.33.3
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus:/etc/prometheus
  alertmanager:
    image: prom/alertmanager:v0.23.0
    ports:
      - '9093:9093'
    volumes:
      - ./alertmanager:/etc/alertmanager
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - '8025:8025'
